/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingFormRouteImport } from './routes/booking-form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSlotsRouteImport } from './routes/admin/slots'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminFoodsRouteImport } from './routes/admin/foods'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAddonsRouteImport } from './routes/admin/addons'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const BookingFormRoute = BookingFormRouteImport.update({
  id: '/booking-form',
  path: '/booking-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin/slots',
  path: '/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/admin/foods',
  path: '/admin/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/admin/addons',
  path: '/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-form'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-form'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/booking-form'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingFormRoute: typeof BookingFormRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/booking-form': {
      id: '/booking-form'
      path: '/booking-form'
      fullPath: '/booking-form'
      preLoaderRoute: typeof BookingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/admin/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/foods': {
      id: '/admin/foods'
      path: '/admin/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/admin/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingFormRoute: BookingFormRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
