/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TncRouteImport } from './routes/tnc'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingFormRouteImport } from './routes/booking-form'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BookingFormSuccessRouteImport } from './routes/booking-form/success'
import { Route as BookingFormReviewRouteImport } from './routes/booking-form/review'
import { Route as BookingFormPackageRouteImport } from './routes/booking-form/package'
import { Route as BookingFormDetailsRouteImport } from './routes/booking-form/details'
import { Route as BookingFormDateSlotRouteImport } from './routes/booking-form/date-slot'
import { Route as BookingFormAddonsFoodsRouteImport } from './routes/booking-form/addons-foods'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSlotsRouteImport } from './routes/admin/slots'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminFoodsRouteImport } from './routes/admin/foods'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBlocksRouteImport } from './routes/admin/blocks'
import { Route as AdminAddonsRouteImport } from './routes/admin/addons'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TncRoute = TncRouteImport.update({
  id: '/tnc',
  path: '/tnc',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormRoute = BookingFormRouteImport.update({
  id: '/booking-form',
  path: '/booking-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BookingFormSuccessRoute = BookingFormSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormReviewRoute = BookingFormReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormPackageRoute = BookingFormPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormDetailsRoute = BookingFormDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormDateSlotRoute = BookingFormDateSlotRouteImport.update({
  id: '/date-slot',
  path: '/date-slot',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormAddonsFoodsRoute = BookingFormAddonsFoodsRouteImport.update({
  id: '/addons-foods',
  path: '/addons-foods',
  getParentRoute: () => BookingFormRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlocksRoute = AdminBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-form': typeof BookingFormRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/payment': typeof PaymentRoute
  '/tnc': typeof TncRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/booking-form/success': typeof BookingFormSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/booking-form': typeof BookingFormRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/payment': typeof PaymentRoute
  '/tnc': typeof TncRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/booking-form/success': typeof BookingFormSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-form': typeof BookingFormRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/payment': typeof PaymentRoute
  '/tnc': typeof TncRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/booking-form/success': typeof BookingFormSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/booking-form'
    | '/login'
    | '/packages'
    | '/payment'
    | '/tnc'
    | '/admin/activities'
    | '/admin/addons'
    | '/admin/blocks'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/users'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/booking-form/success'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/booking-form'
    | '/login'
    | '/packages'
    | '/payment'
    | '/tnc'
    | '/admin/activities'
    | '/admin/addons'
    | '/admin/blocks'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/users'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/booking-form/success'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/booking-form'
    | '/login'
    | '/packages'
    | '/payment'
    | '/tnc'
    | '/admin/activities'
    | '/admin/addons'
    | '/admin/blocks'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/users'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/booking-form/success'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingFormRoute: typeof BookingFormRouteWithChildren
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  PaymentRoute: typeof PaymentRoute
  TncRoute: typeof TncRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tnc': {
      id: '/tnc'
      path: '/tnc'
      fullPath: '/tnc'
      preLoaderRoute: typeof TncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-form': {
      id: '/booking-form'
      path: '/booking-form'
      fullPath: '/booking-form'
      preLoaderRoute: typeof BookingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/booking-form/success': {
      id: '/booking-form/success'
      path: '/success'
      fullPath: '/booking-form/success'
      preLoaderRoute: typeof BookingFormSuccessRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/review': {
      id: '/booking-form/review'
      path: '/review'
      fullPath: '/booking-form/review'
      preLoaderRoute: typeof BookingFormReviewRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/package': {
      id: '/booking-form/package'
      path: '/package'
      fullPath: '/booking-form/package'
      preLoaderRoute: typeof BookingFormPackageRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/details': {
      id: '/booking-form/details'
      path: '/details'
      fullPath: '/booking-form/details'
      preLoaderRoute: typeof BookingFormDetailsRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/date-slot': {
      id: '/booking-form/date-slot'
      path: '/date-slot'
      fullPath: '/booking-form/date-slot'
      preLoaderRoute: typeof BookingFormDateSlotRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/addons-foods': {
      id: '/booking-form/addons-foods'
      path: '/addons-foods'
      fullPath: '/booking-form/addons-foods'
      preLoaderRoute: typeof BookingFormAddonsFoodsRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/foods': {
      id: '/admin/foods'
      path: '/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocks': {
      id: '/admin/blocks'
      path: '/blocks'
      fullPath: '/admin/blocks'
      preLoaderRoute: typeof AdminBlocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminBlocksRoute: typeof AdminBlocksRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminBlocksRoute: AdminBlocksRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookingFormRouteChildren {
  BookingFormAddonsFoodsRoute: typeof BookingFormAddonsFoodsRoute
  BookingFormDateSlotRoute: typeof BookingFormDateSlotRoute
  BookingFormDetailsRoute: typeof BookingFormDetailsRoute
  BookingFormPackageRoute: typeof BookingFormPackageRoute
  BookingFormReviewRoute: typeof BookingFormReviewRoute
  BookingFormSuccessRoute: typeof BookingFormSuccessRoute
}

const BookingFormRouteChildren: BookingFormRouteChildren = {
  BookingFormAddonsFoodsRoute: BookingFormAddonsFoodsRoute,
  BookingFormDateSlotRoute: BookingFormDateSlotRoute,
  BookingFormDetailsRoute: BookingFormDetailsRoute,
  BookingFormPackageRoute: BookingFormPackageRoute,
  BookingFormReviewRoute: BookingFormReviewRoute,
  BookingFormSuccessRoute: BookingFormSuccessRoute,
}

const BookingFormRouteWithChildren = BookingFormRoute._addFileChildren(
  BookingFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingFormRoute: BookingFormRouteWithChildren,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  PaymentRoute: PaymentRoute,
  TncRoute: TncRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
