/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as BookingFormRouteImport } from './routes/booking-form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BookingFormReviewRouteImport } from './routes/booking-form/review'
import { Route as BookingFormPackageRouteImport } from './routes/booking-form/package'
import { Route as BookingFormDetailsRouteImport } from './routes/booking-form/details'
import { Route as BookingFormDateSlotRouteImport } from './routes/booking-form/date-slot'
import { Route as BookingFormAddonsFoodsRouteImport } from './routes/booking-form/addons-foods'
import { Route as AdminSlotsRouteImport } from './routes/admin/slots'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminFoodsRouteImport } from './routes/admin/foods'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAddonsRouteImport } from './routes/admin/addons'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormRoute = BookingFormRouteImport.update({
  id: '/booking-form',
  path: '/booking-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormReviewRoute = BookingFormReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormPackageRoute = BookingFormPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormDetailsRoute = BookingFormDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormDateSlotRoute = BookingFormDateSlotRouteImport.update({
  id: '/date-slot',
  path: '/date-slot',
  getParentRoute: () => BookingFormRoute,
} as any)
const BookingFormAddonsFoodsRoute = BookingFormAddonsFoodsRouteImport.update({
  id: '/addons-foods',
  path: '/addons-foods',
  getParentRoute: () => BookingFormRoute,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin/slots',
  path: '/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/admin/foods',
  path: '/admin/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/admin/addons',
  path: '/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRouteWithChildren
  '/packages': typeof PackagesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRouteWithChildren
  '/packages': typeof PackagesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-form': typeof BookingFormRouteWithChildren
  '/packages': typeof PackagesRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking-form/addons-foods': typeof BookingFormAddonsFoodsRoute
  '/booking-form/date-slot': typeof BookingFormDateSlotRoute
  '/booking-form/details': typeof BookingFormDetailsRoute
  '/booking-form/package': typeof BookingFormPackageRoute
  '/booking-form/review': typeof BookingFormReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-form'
    | '/packages'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-form'
    | '/packages'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/booking-form'
    | '/packages'
    | '/admin/addons'
    | '/admin/bookings'
    | '/admin/discounts'
    | '/admin/foods'
    | '/admin/packages'
    | '/admin/slots'
    | '/booking-form/addons-foods'
    | '/booking-form/date-slot'
    | '/booking-form/details'
    | '/booking-form/package'
    | '/booking-form/review'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingFormRoute: typeof BookingFormRouteWithChildren
  PackagesRoute: typeof PackagesRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-form': {
      id: '/booking-form'
      path: '/booking-form'
      fullPath: '/booking-form'
      preLoaderRoute: typeof BookingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-form/review': {
      id: '/booking-form/review'
      path: '/review'
      fullPath: '/booking-form/review'
      preLoaderRoute: typeof BookingFormReviewRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/package': {
      id: '/booking-form/package'
      path: '/package'
      fullPath: '/booking-form/package'
      preLoaderRoute: typeof BookingFormPackageRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/details': {
      id: '/booking-form/details'
      path: '/details'
      fullPath: '/booking-form/details'
      preLoaderRoute: typeof BookingFormDetailsRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/date-slot': {
      id: '/booking-form/date-slot'
      path: '/date-slot'
      fullPath: '/booking-form/date-slot'
      preLoaderRoute: typeof BookingFormDateSlotRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/booking-form/addons-foods': {
      id: '/booking-form/addons-foods'
      path: '/addons-foods'
      fullPath: '/booking-form/addons-foods'
      preLoaderRoute: typeof BookingFormAddonsFoodsRouteImport
      parentRoute: typeof BookingFormRoute
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/admin/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/foods': {
      id: '/admin/foods'
      path: '/admin/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/admin/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingFormRouteChildren {
  BookingFormAddonsFoodsRoute: typeof BookingFormAddonsFoodsRoute
  BookingFormDateSlotRoute: typeof BookingFormDateSlotRoute
  BookingFormDetailsRoute: typeof BookingFormDetailsRoute
  BookingFormPackageRoute: typeof BookingFormPackageRoute
  BookingFormReviewRoute: typeof BookingFormReviewRoute
}

const BookingFormRouteChildren: BookingFormRouteChildren = {
  BookingFormAddonsFoodsRoute: BookingFormAddonsFoodsRoute,
  BookingFormDateSlotRoute: BookingFormDateSlotRoute,
  BookingFormDetailsRoute: BookingFormDetailsRoute,
  BookingFormPackageRoute: BookingFormPackageRoute,
  BookingFormReviewRoute: BookingFormReviewRoute,
}

const BookingFormRouteWithChildren = BookingFormRoute._addFileChildren(
  BookingFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingFormRoute: BookingFormRouteWithChildren,
  PackagesRoute: PackagesRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
